[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.15'

rpc_endpoints = { MAINNET = "${MAINNET_RPC}", ARBITRUM = "${ARBITRUM_RPC}", UNIT_TESTS = "https://rpc.tenderly.co/fork/eb4cc00e-c12c-45f5-905a-04f0cfdefa2f", HARNESS = "https://rpc.tenderly.co/fork/5d734736-afd1-485d-b18c-d51453425706" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config